{% set name = "freephil" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/freephil-{{ version }}.tar.gz
  sha256: 71b3d32b0908571548a5f04ffa206d061648fd39438d432e9f7bca4f0db4063e

build:
  number: 1
  noarch: python
  entry_points:
    - phil = freephil.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - freephil
  commands:
    - pip check
    - phil --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/freephil/
  summary: A free command line parsing library
  license: BSD-3-Clause AND BSD-3-Clause-LBNL
  license_file:
    - LICENSE
    - LICENSE_LIBTBX
  dev_url: https://github.com/Anthchirp/freephil/
  doc_url: https://freephil.readthedocs.io/

extra:
  recipe-maintainers:
    - rjgildea
    - ndevenish
    - anthchirp
